### ISSUE TITLE
Development and Deployment instructions

### ISSUE THREAD

**Issue by egeldenhuys** [TripleParity/docks-api#56]
- [x] Describe workflow used for development
- [x] Describe workflow for deploying the latest version of docks-api
- [x] Describe workflow for building and deploying docks-api on a swarm

**Comment by devosray** [comment]
The "Docker Only" approach seems to be out of date now since it does not include the PostgreSQL server.

The instructions "`$ docker-compose up`" is also incorrect as the default compose file pulls the image from Docker hub instead of building it locally.

I assume no one is using the Docker-only workflow any more and thus I propose we delete it?

**Comment by egeldenhuys** [comment]
TODO:
- [ ] Delete docker-compose workflow as it does not support swarm mode
